receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  otlphttp/grafana_cloud:
    endpoint: "${env:GRAFANA_OTLP_ENDPOINT}"
    auth:
      authenticator: basicauth/grafana_cloud

  debug:
    verbosity: detailed

extensions:
  basicauth/grafana_cloud:
    client_auth:
      username: "${env:GRAFANA_OTLP_INSTANCE_ID}"
      password: "${env:GRAFANA_OTLP_TOKEN}"

service:
  extensions: [basicauth/grafana_cloud]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/grafana_cloud, debug]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/grafana_cloud, debug]
